### ISSUE TITLE
Can't find files

### ISSUE THREAD

**Issue by s-corley** [MarttiR/searchkit-datefilter#2]
I have datefilter in my node_modules but when I try to add it in my searchkit app I get all the following warnings and my app doesn't load. It imports fine so it shouldn't have been an installation issue. Any ideas? thanks

`WARNING in ./~/searchkit-datefilter/dist/src/index.js
(Emitted value instead of an instance of Error) Cannot find source file '../../src/index.ts': Error: Can't resolve '../../src/index.ts' in '/home/emman/proj/node_modules/searchkit-datefilter/dist/src'
 @ ./src/index.tsx 16:29-60

WARNING in ./~/searchkit-datefilter/dist/src/DateRangeCalendar.js
(Emitted value instead of an instance of Error) Cannot find source file '../../src/DateRangeCalendar.tsx': Error: Can't resolve '../../src/DateRangeCalendar.tsx' in '/home/emman/proj/node_modules/searchkit-datefilter/dist/src'
 @ ./~/searchkit-datefilter/dist/src/index.js 7:9-39
 @ ./src/index.tsx

WARNING in ./~/searchkit-datefilter/dist/src/DateRangeAccessor.js
(Emitted value instead of an instance of Error) Cannot find source file '../../src/DateRangeAccessor.ts': Error: Can't resolve '../../src/DateRangeAccessor.ts' in '/home/emman/proj/node_modules/searchkit-datefilter/dist/src'
 @ ./~/searchkit-datefilter/dist/src/index.js 6:9-39
 @ ./src/index.tsx

WARNING in ./~/searchkit-datefilter/dist/src/DateRangeFilter.js
(Emitted value instead of an instance of Error) Cannot find source file '../../src/DateRangeFilter.tsx': Error: Can't resolve '../../src/DateRangeFilter.tsx' in '/home/emman/proj/node_modules/searchkit-datefilter/dist/src'
 @ ./~/searchkit-datefilter/dist/src/index.js 8:9-37
 @ ./src/index.tsx

WARNING in ./~/searchkit-datefilter/dist/src/DateRangeQuery.js
(Emitted value instead of an instance of Error) Cannot find source file '../../src/DateRangeQuery.ts': Error: Can't resolve '../../src/DateRangeQuery.ts' in '/home/emman/proj/node_modules/searchkit-datefilter/dist/src'
 @ ./~/searchkit-datefilter/dist/src/index.js 9:9-36
 @ ./src/index.tsx
`

**Comment by MarttiR** [comment]
This seems related to webpack loader configuration.

https://github.com/apollographql/react-apollo/issues/597#issuecomment-292083184

> In my webpack config I have the source-maps-loader but didn't exclude node_modules and this seemed to be causing the issue. Adding the exclude fixed it for me.

**Comment by s-corley** [comment]
Awesome, thank you. I fixed it by excluding node_modules and also installing css-raw-loader
